[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = [
        "*/.*",
    ]

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = [
        "*/.editorconfig",
        "*/.gitattributes",
        "*/.github",
        "*/.gitignore",
    ]

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = [
        "*/.editorconfig",
        "*/.github",
        "*/.gitignore",
    ]

[".config/tmux/plugins/tpm"]
    url = "https://github.com/tmux-plugins/tpm"
    type = "git-repo"

[".config/tmux/plugins/catppuccin/tmux"]
    type = "archive"
    url = "https://github.com/catppuccin/tmux/archive/refs/tags/v2.1.2.tar.gz"
    exact = true
    stripComponents = 1
