[".config/tmux/plugins/tpm"]
    url = "https://github.com/tmux-plugins/tpm"
    type = "git-repo"

[".config/tmux/plugins/catppuccin/tmux"]
    type = "archive"
    url = "https://github.com/catppuccin/tmux/archive/refs/tags/v2.1.1.tar.gz"
    exact = true
    stripComponents = 1
