
[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Light" }
size = 20

[window]
decorations = "Full"
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

